name: Telegram Bot Run

on:
  schedule:
    # 매시간 3분, 18분, 33분, 48분에 실행 (경쟁자가 적음)
    - cron: '3,18,33,48 * * * *'
  workflow_dispatch:      # 수동 실행 버튼 추가

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install libraries
        run: |
          pip install telethon requests

      - name: Run bot script
        env:
          API_ID: ${{ secrets.API_ID }}
          API_HASH: ${{ secrets.API_HASH }}
          TELEGRAM_SESSION: ${{ secrets.TELEGRAM_SESSION }}
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}  # <--- 이 줄을 꼭 추가해야 합니다!
        run: python bot.py
