name: Telegram Bot Run

# [핵심] 중복 프로세스 강제 종료 로직 (동시성 제어)
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

on:
  schedule:
    - cron: '3,18,33,48 * * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install libraries
        run: |
          pip install telethon requests

      - name: Run bot script
        env:
          API_ID: ${{ secrets.API_ID }}
          API_HASH: ${{ secrets.API_HASH }}
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          # [수정] 1번 세션 키 할당
          TELEGRAM_SESSION_1: ${{ secrets.TELEGRAM_SESSION_1 }} 
        run: python bot.py
